export const mockData = [
  {
    eff_date: '01/01/2025',
    shares_per_par: '1,541,751.13',
    trans_cd: '1-10 STATE DEPOSITS',
    memo_nbr: 3382101,
    location_cd: 'CA',
    acct_nbr: 'CA-505',
  },
  {
    eff_date: '01/01/2025',
    shares_per_par: '1,541,751.13',
    trans_cd: '1-10 STATE DEPOSITS',
    memo_nbr: 3382101,
    location_cd: '',
    acct_nbr: 'CA-505',
  },
  {
    eff_date: '01/03/2025',
    shares_per_par: '732,100.56',
    trans_cd: '34-10 LOAN REPAYMENT FROM STATE TO FUA',
    memo_nbr: 3382107,
    location_cd: 'CA',
    acct_nbr: 'CA-505',
  },
  {
    eff_date: '01/10/2025',
    shares_per_par: '-2,875,442.00',
    trans_cd: '31-50 GT TO STATE UI ACCOUNT',
    memo_nbr: 3382108,
    location_cd: '',
    acct_nbr: 'CA-505',
  },
  {
    eff_date: '01/10/2025',
    shares_per_par: '-2,875,442.00',
    trans_cd: '31-50 GT TO STATE UI ACCOUNT',
    memo_nbr: 3382108,
    location_cd: 'CA',
    acct_nbr: 'CA-505',
  },
  {
    eff_date: '01/14/2025',
    shares_per_par: '485,190.99',
    trans_cd: 'CWC OUT',
    memo_nbr: 3382110,
    location_cd: 'CA',
    acct_nbr: 'CA-505',
  },
  {
    eff_date: '01/15/2025',
    shares_per_par: '3,167,250.00',
    trans_cd: 'CWC IN',
    memo_nbr: 3382112,
    location_cd: 'CA',
    acct_nbr: 'CA-505',
  },
  {
    eff_date: '01/20/2025',
    shares_per_par: '1,250,000.00',
    trans_cd: 'LOAN REPAYMENT',
    memo_nbr: 3382113,
    location_cd: 'CA',
    acct_nbr: 'CA-505',
  },
  {
    eff_date: '01/20/2025',
    shares_per_par: '1,250,000.00',
    trans_cd: 'LOAN REPAYMENT',
    memo_nbr: 3382113,
    location_cd: '',
    acct_nbr: 'CA-505',
  },
];
export const mockData2 = [
  {
    trans_desc_cd: '11-10 STATE DEPOSITS',
    shares_per_par: '$1,541,751.13',
  },
  {
    trans_desc_cd: '11-10 LOAN REPAYMENT',
    shares_per_par: '$751.13',
  },
  {
    trans_desc_cd: '11-10 LOAN REPAYMENT FROM STATE TO FUA',
    shares_per_par: '$541,751.13',
  },
  {
    trans_desc_cd: '11-10 CWC IN',
    shares_per_par: '$54,751.13',
  },
];

export const accountStatementFebData = {
  data: [
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-26',
      shares_per_par: '1942000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376319',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '26',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-25',
      shares_per_par: '-7867000.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376300',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '25',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-24',
      shares_per_par: '20751000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376282',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '24',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-21',
      shares_per_par: '-23624.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-40 PAYMENTS TO DOL DEPT. MAN.',
      memo_nbr: '3376259',
      location_cd: 'D1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '21',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-21',
      shares_per_par: '2946000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376260',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '21',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-20',
      shares_per_par: '3051000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376237',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '20',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-19',
      shares_per_par: '-15000000.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-20 PAY DOL FOR GRANTS TO STATES',
      memo_nbr: '3376214',
      location_cd: 'D1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '19',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-19',
      shares_per_par: '-55000000.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-20 PAY DOL FOR GRANTS TO STATES',
      memo_nbr: '3376215',
      location_cd: 'D1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '19',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-19',
      shares_per_par: '-20000000.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-20 PAY DOL FOR GRANTS TO STATES',
      memo_nbr: '3376216',
      location_cd: 'D1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '19',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-19',
      shares_per_par: '-6000000.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-20 PAY DOL FOR GRANTS TO STATES',
      memo_nbr: '3376217',
      location_cd: 'D1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '19',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-19',
      shares_per_par: '-250000000.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-20 PAY DOL FOR GRANTS TO STATES',
      memo_nbr: '3376218',
      location_cd: 'D1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '19',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-19',
      shares_per_par: '3477000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376219',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '19',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-18',
      shares_per_par: '6903000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376196',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '18',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-14',
      shares_per_par: '-6249454.36',
      trans_cd: 'PARW+',
      trans_desc_cd: '12-11 FUTA ADJUSTMENTS',
      memo_nbr: '3376169',
      location_cd: 'M1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '14',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-14',
      shares_per_par: '5238000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376170',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '14',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-14',
      shares_per_par: '-4142950.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-30 PAY DOL FOR S and E EMPTRN',
      memo_nbr: '3376171',
      location_cd: 'D1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '14',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-14',
      shares_per_par: '-5215600.00',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-60 PAYMENTS TO DOL - BLS',
      memo_nbr: '3376172',
      location_cd: 'D1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '14',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-13',
      shares_per_par: '3206000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376145',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '13',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-12',
      shares_per_par: '-45285.75',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-85 PAY BPD FOR TREASURY ADMIN EXP',
      memo_nbr: '3376124',
      location_cd: 'M1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '12',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-12',
      shares_per_par: '-4539647.89',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-70 FUTA REF TO IRS PRIN CY ',
      memo_nbr: '3376125',
      location_cd: 'M1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '12',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-12',
      shares_per_par: '-471268.63',
      trans_cd: 'PARW+',
      trans_desc_cd: '22-72 FUTA REFUNDS TO IRS INTEREST ',
      memo_nbr: '3376126',
      location_cd: 'M1',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '12',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-12',
      shares_per_par: '5338000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376127',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '12',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-11',
      shares_per_par: '4732000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376106',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '11',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-10',
      shares_per_par: '8387000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376088',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '10',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-07',
      shares_per_par: '6137000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3376066',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '07',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-06',
      shares_per_par: '8133000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3375992',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '06',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-05',
      shares_per_par: '13121000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3375963',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '05',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-04',
      shares_per_par: '8580000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3375944',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '04',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-03',
      shares_per_par: '2076300000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3375925',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '03',
    },
    {
      acct_statement: '000000000000562',
      eff_date: '2025-02-03',
      shares_per_par: '29474000.00',
      trans_cd: 'PARC+',
      trans_desc_cd: '12-10 FUTA RECEIPTS',
      memo_nbr: '3375926',
      location_cd: 'null',
      acct_nbr: 'ESAA',
      acct_desc: 'ESAA',
      report_type: 'Federal',
      record_fiscal_year: '2025',
      record_fiscal_quarter: '2',
      record_calendar_year: '2025',
      record_calendar_quarter: '1',
      record_calendar_month: '02',
      record_calendar_day: '03',
    },
  ],
  meta: {
    count: 30,
    labels: {
      acct_statement: 'Account Statement',
      eff_date: 'Effective Date',
      shares_per_par: 'Shares / Par',
      trans_cd: 'Trans Code',
      trans_desc_cd: 'Transaction Description Code',
      memo_nbr: 'Memo Number',
      location_cd: 'Location',
      acct_nbr: 'Account Number',
      acct_desc: 'Account Description',
      report_type: 'Report Type',
      record_fiscal_year: 'Fiscal Year',
      record_fiscal_quarter: 'Fiscal Quarter Number',
      record_calendar_year: 'Calendar Year',
      record_calendar_quarter: 'Calendar Quarter Number',
      record_calendar_month: 'Calendar Month Number',
      record_calendar_day: 'Calendar Day Number',
    },
    dataTypes: {
      acct_statement: 'STRING',
      eff_date: 'DATE',
      shares_per_par: 'NUMBER',
      trans_cd: 'STRING',
      trans_desc_cd: 'STRING',
      memo_nbr: 'STRING',
      location_cd: 'STRING',
      acct_nbr: 'STRING',
      acct_desc: 'STRING',
      report_type: 'STRING',
      record_fiscal_year: 'YEAR',
      record_fiscal_quarter: 'QUARTER',
      record_calendar_year: 'YEAR',
      record_calendar_quarter: 'QUARTER',
      record_calendar_month: 'MONTH',
      record_calendar_day: 'DAY',
    },
    dataFormats: {
      acct_statement: 'String',
      eff_date: 'YYYY-MM-DD',
      shares_per_par: '10.2',
      trans_cd: 'String',
      trans_desc_cd: 'String',
      memo_nbr: 'String',
      location_cd: 'String',
      acct_nbr: 'String',
      acct_desc: 'String',
      report_type: 'String',
      record_fiscal_year: 'YYYY',
      record_fiscal_quarter: 'Q',
      record_calendar_year: 'YYYY',
      record_calendar_quarter: 'Q',
      record_calendar_month: 'MM',
      record_calendar_day: 'DD',
    },
    'total-count': 30,
    'total-pages': 1,
  },
};

export const mockDataColConfig = {
  eff_date: { width: 60, prettyName: 'Effective Date' },
  shares_per_par: { width: 50, prettyName: 'Shares / Par' },
  trans_cd: { width: 190, prettyName: 'Transaction Code' },
  memo_nbr: { width: 60, prettyName: 'Memo Number' },
  location_cd: { width: 50, prettyName: 'Location' },
  acct_nbr: { width: 70, prettyName: 'Account Number' },
  trans_desc_cd: { width: 130, prettyName: 'Transaction Description' },
};
export const mockData2ColConfig = {
  shares_per_par: { width: 20, prettyName: 'Shares / Par', style: { textAlign: 'right' } },
  trans_desc_cd: { width: 180, prettyName: 'Transaction Description' },
};

// 563 total width
export const accountStatementReportConfig = {
  documentTitle: 'Account Statement Report',
  documentHeader: [
    { name: 'Account', value: 'CALIFORNIA, 0000000000000000' },
    { name: 'Report Date', value: 'January 2025' },
    { name: 'Final Report', style: 'final' },
    { name: 'Beginning Balance', value: '$12345' },
    { name: 'Ending Balance', value: '$678910' },
  ],
  tables: [
    {
      width: '100%',
      fields: [
        { name: 'eff_date', width: 70 },
        { name: 'shares_per_par', width: 70 },
        { name: 'trans_cd', width: 53 },
        { name: 'trans_desc_cd', width: 180 },
        { name: 'memo_nbr', width: 70 },
        { name: 'location_cd', width: 50 },
        { name: 'acct_nbr', width: 70 },
      ],
    },
  ],
};

export const config = {
  fields: [
    {
      columnName: 'acct_statement',
      dataType: 'STRING',
      definition: 'The account number assigned to the State selected for Choose an Account.',
      isRequired: 1,
      prettyName: 'Account Statement',
      tableName: 'Account Statement',
    },
    {
      columnName: 'eff_date',
      dataType: 'DATE',
      definition: 'The effective date of the actual activity populated on the line.',
      isRequired: 1,
      prettyName: 'Effective Date',
    },
    {
      columnName: 'shares_per_par',
      dataType: 'NUMBER',
      definition: 'The debit or credit amount associated with the transaction.',
      isRequired: 1,
      prettyName: 'Shares / Par',
    },
    {
      columnName: 'trans_cd',
      dataType: 'STRING',
      definition: 'The code associated with the transaction description.',
      isRequired: 1,
      prettyName: 'Trans Code',
    },
    {
      columnName: 'trans_desc_cd',
      dataType: 'STRING',
      definition: 'The description of the transaction code.',
      isRequired: 1,
      prettyName: 'Transaction Description Code',
    },
    {
      columnName: 'memo_nbr',
      dataType: 'STRING',
      definition: 'The memo number for a specific transaction.',
      isRequired: 1,
      prettyName: 'Memo Number',
    },
    {
      columnName: 'location_cd',
      dataType: 'STRING',
      definition: 'The 2 digit state code representing the location of the transaction.',
      isRequired: 1,
      prettyName: 'Location',
    },
    {
      columnName: 'acct_nbr',
      dataType: 'STRING',
      definition: 'Represents the state code or federal value selected for a specific account statement.',
      isRequired: 1,
      prettyName: 'Account Number',
    },
    {
      columnName: 'acct_desc',
      dataType: 'STRING',
      definition: 'The description of the state code or federal value selected for a specific account statement.',
      isRequired: 1,
      prettyName: 'Account Description',
    },
    {
      columnName: 'report_type',
      dataType: 'STRING',
      definition: 'Represents whether the transaction is associated with a state or federal account statement.',
      isRequired: 1,
      prettyName: 'Report Type',
    },
    {
      columnName: 'record_fiscal_year',
      dataType: 'YEAR',
      definition: 'The fiscal year associated with record_date. The f… fiscal year runs from October 1 to September 30.',
      isRequired: 1,
      prettyName: 'Fiscal Year',
    },
    {
      columnName: 'record_fiscal_quarter',
      dataType: 'QUARTER',
      definition: 'The fiscal quarter associated with record_date. Fo…arch, Q3 - April to June, Q4 - July to September.',
      isRequired: 1,
      prettyName: 'Fiscal Quarter Number',
    },
    {
      columnName: 'record_calendar_year',
      dataType: 'YEAR',
      definition: 'The calendar year associated with record_date.',
      isRequired: 1,
      prettyName: 'Calendar Year',
    },
    {
      columnName: 'record_calendar_quarter',
      dataType: 'QUARTER',
      definition: 'The calendar quarter associated with record_date.',
      isRequired: 1,
      prettyName: 'Calendar Quarter Number',
    },
    {
      columnName: 'record_calendar_month',
      dataType: 'MONTH',
      definition: 'The calendar month associated with record_date.',
      isRequired: 1,
      prettyName: 'Calendar Month Number',
    },
    {
      columnName: 'record_calendar_day',
      dataType: 'DAY',
      definition: 'The calendar day associated with record_date.',
      isRequired: 1,
      prettyName: 'Calendar Day Number',
    },
  ],
};
