// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const star: string;
export const bedazzle: string;
export const alternate: string;
export const bedazzleAlt: string;
export const sparkleBox: string;
