// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const downloadContainer: string;
export const downloadIcon: string;
export const downloadButton: string;
