import React, {useState} from "react";
import TotalRevenueChart
  from "./government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart";
import useBeaGDP from "../../../../../hooks/useBeaGDP";
import { faMapLocationDot } from '@fortawesome/free-solid-svg-icons';
import Accordion from "../../../../../components/accordion/accordion";
import CustomLink from "../../../../../components/links/custom-link/custom-link";
import QuoteBox from "../../../quote-box/quote-box";
import {revenueExplainerPrimary, revenueExplainerLightSecondary, revenueAccordion}
  from "../revenue.module.scss";
import {quoteBoxContent} from "../../../explainer.module.scss";


const FederalRevenueTrendsAndUSEconomy = ({cpiDataByYear}) => {
  const beaGDPData = useBeaGDP(cpiDataByYear);

  const [fiscalYear, setFiscalYear] = useState(2022);
  const [revenueRatio, setRevenueRatio] = useState('');
  const [revenueTotal, setRevenueTotal] = useState('');

  const callBackDataToPage  = (data) =>{
    setFiscalYear(data.fiscalYear);
    setRevenueRatio(data.revenueRatio);
    setRevenueTotal(data.revenueTotal);
  }

  const federalReserveAct = (
    <CustomLink url={'https://www.federalreserve.gov/aboutthefed/section7.htm'} >
      Federal Reserve Act, Section 7(a)(1-3)
    </CustomLink>
  );

  const gps = (
    <CustomLink url={'https://www.gps.gov/policy/funding/'} >
      GPS.gov
    </CustomLink>
  );

  return (
    <>
      <p>
        In fiscal year {fiscalYear}, federal revenue was
        equal to {revenueRatio} of total gross domestic product (GDP), or economic
        activity, of the United States that year ${revenueTotal}.
      </p>
      <p>
        Why do we compare federal revenue to gross domestic product? The
        comparison serves as a rough gauge of the size of the federal
        government's footprint related to size of the country's economic
        activity. Since federal taxes are based on a percentage of income for
        people and businesses, as people and businesses earn more the federal
        revenue from taxes increases.
      </p>
      {!beaGDPData.isGDPLoading && (
        <TotalRevenueChart
          cpiDataByYear={cpiDataByYear}
          beaGDPData={beaGDPData}
          copyPageData={callBackDataToPage}
        />
      )}
      <QuoteBox icon={faMapLocationDot}
                primaryColor={revenueExplainerPrimary}
                secondaryColor={revenueExplainerLightSecondary}
      >
        <p className={quoteBoxContent}>
          Free GPS (Global Positioning System) service enjoyed throughout the world is funded
          by general U.S. tax revenues.
          <br />
          <span style={{ fontSize: "16px" }}>Source: {gps}</span>
        </p>
      </QuoteBox>
      <div className={revenueAccordion}>
        <Accordion title={'Why does the Federal Reserve send money to the federal government?'}>
          The Federal Reserve Act of 1913, the law that created the Federal Reserve System and
          established it as the central bank of the United States, requires that any excess
          earnings generated by 12 Federal Reserve Banks be paid to the federal government.
          In practice, Federal Reserve banks pay for their operating expenses, pay a dividend
          to stockholders (U.S. commercial banks), set aside money in a surplus fund (capped at
          $6.8 billion), and the remainder is “transferred…to the Secretary of the Treasury for
          deposit in the general fund of the Treasury.” [<i>See</i> {federalReserveAct}]
        </Accordion>
      </div>
    </>
  );
};

export default FederalRevenueTrendsAndUSEconomy;
