// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footerStyle: string;
export const headerContainer: string;
export const headerStyle: string;
export const subHeader: string;
export const column: string;
export const chartsContainer: string;
export const percentOrDollarContainer: string;
export const descContainer: string;
export const chartToggle: string;
export const toggleButton: string;
