// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const tableStyle: string;
export const divTable: string;
export const tr: string;
export const th: string;
export const td: string;
