// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const linkDiv: string;
export const linkSeparator: string;
export const currentPage: string;
