// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const barDiv: string;
export const linkDiv: string;
export const dot: string;
export const toolTip: string;
export const fallback: string;
