module.exports = {
  ENV_ID: 'qat',
  BASE_URL: 'https://qat.fiscaldata.treasury.gov',
  API_BASE_URL: 'https://api.fiscaldata.treasury.gov',
  DATA_DOWNLOAD_BASE_URL: 'https://fiscaldata.treasury.gov',
  WEB_SOCKET_BASE_URL: 'wss://downloads.fiscaldata.treasury.gov/main',
  EXPERIMENTAL_WHITELIST: ['experimental-page', 'afg-overview', 'publishedReportsSection'],
  ADDITIONAL_DATASETS: {
    '015-BFS-2014Q3-053': {
      slug: '/unemployment-trust-funds-report-selection/',
      seoConfig: {
        pageTitle: 'Unemployment Trust Funds Report Selection',
        description:
          'Unemployment Trust Fund Report Selection offers numerous reports by month, year, state, federal, ' +
          'and report type. The reports represent data supporting the Account Statement, Transaction Statement, ' +
          'and the Federal Activity Statement reports. The Unemployment Trust Fund is made up of 59 U.S. Treasury ' +
          'accounts, including an account for each state and some territories.',
        keywords: 'Debt, Financial Summaries',
      },
      topics: ['debt', 'financial-summaries'],
      relatedDatasets: ['015-BFS-2014Q3-093'],
      currentDateButton: 'byFullMonth',
    },
    '015-BFS-2024Q1-003': {
      slug: '/fbp-detailed-principal-accrued-interest/',
      seoConfig: {
        pageTitle: 'Federal Borrowings Program: Detailed Principal and Accrued Interest Report',
        description:
          "U.S. Treasury loans and interest receivable balances associated with each individual borrowing agency's expenditure Treasury Account Symbol.",
        keywords: 'Debt, Financial Summaries',
      },
      topics: ['debt', 'financial-summaries'],
      relatedDatasets: ['015-BFS-2014Q3-038', '015-BFS-2014Q3-037'],
      currentDateButton: 'byMonth',
      displayApiFilterForAllTables: true
    },
  },
  USE_MOCK_RELEASE_CALENDAR_DATA_ON_API_FAIL: true,
  ADDITIONAL_ENDPOINTS: {
    '305': {
      endpoint: 'v1/accounting/od/utf_account_statement',
      dateField: 'eff_date',
      downloadName: 'UTF_Account_Statement ',
      alwaysSortWith: ['acct_desc', '-eff_date', 'memo_nbr'],
      apiFilter: {
        field: 'acct_desc',
        downloadLabel: 'Account',
        label: 'Choose a Federal or State Account',
        dataUnmatchedHeader: 'There is no data to display based on the current filters selected.',
        dataUnmatchedMessage: 'Select a different account description and/or date range in order to preview the data.',
        dataDefaultHeader: 'This table requires additional filters.',
        dataDefaultMessage: 'Select an account in the filter section above to display the data.',
        dataSearchLabel: 'Search account descriptions',
        notice: `Effective Dates on Fiscal Data may differ from the published effective dates for corresponding reports on TreasuryDirect.`,
        fieldFilter: {
          field: 'report_type',
          value: ['Federal', 'State'],
        },
      },
      selectColumns: [
        'acct_statement',
        'eff_date',
        'shares_per_par',
        'trans_cd',
        'trans_desc_cd',
        'memo_nbr',
        'location_cd',
        'acct_nbr',
        'acct_desc',
        'report_type',
      ],
    },
    '306': {
      endpoint: 'v1/accounting/od/utf_transaction_statement',
      dateField: 'eff_date',
      downloadName: 'UTF_Transaction_Statement ',
      alwaysSortWith: ['acct_desc', '-eff_date', 'memo_nbr'],
      apiFilter: {
        field: 'acct_desc',
        downloadLabel: 'Account',
        label: 'Choose a Federal or State Account',
        dataUnmatchedHeader: 'There is no data to display based on the current filters selected.',
        dataUnmatchedMessage: 'Select a different account description and/or date range in order to preview the data.',
        dataDefaultHeader: 'This table requires additional filters.',
        dataDefaultMessage: 'Select an account in the filter section above to display the data.',
        dataSearchLabel: 'Search account descriptions',
        notice: `Effective Dates on Fiscal Data may differ from the published effective dates for corresponding reports on TreasuryDirect.`,
        fieldFilter: {
          field: 'report_type',
          value: ['Federal', 'State'],
        },
      },
      selectColumns: [
        'trans_statement',
        'eff_date',
        'shares_per_par',
        'trans_desc_cd',
        'memo_nbr',
        'location_cd',
        'acct_nbr',
        'acct_desc',
        'report_type',
      ],
    },
    '307': {
      endpoint: 'v1/accounting/od/utf_federal_activity_statement',
      dateField: 'eff_date',
      downloadName: 'UTF_Federal_Activity_Statement ',
      alwaysSortWith: ['acct_desc', '-eff_date', 'memo_nbr'],
      apiFilter: {
        field: 'acct_desc',
        downloadLabel: 'Account',
        label: 'Choose a State Account',
        dataUnmatchedHeader: 'There is no data to display based on the current filters selected.',
        dataUnmatchedMessage: 'Select a different account description and/or date range in order to preview the data.',
        dataDefaultHeader: 'This table requires additional filters.',
        dataDefaultMessage: 'Select an account in the filter section above to display the data.',
        dataSearchLabel: 'Search account descriptions',
        notice: `Effective Dates on Fiscal Data may differ from the published effective dates for corresponding reports on TreasuryDirect.`,
      },
      selectColumns: ['fed_act_statement', 'eff_date', 'shares_per_par', 'trans_desc_cd', 'memo_nbr', 'location_cd', 'acct_nbr', 'acct_desc'],
    },
    //FBP
    '313': {
      endpoint: 'v1/accounting/od/fbp_balances',
      dateField: 'record_date',
      downloadName: 'FBP_Balances',
      alwaysSortWith: ['-sort_order_primary', '-sort_order_secondary', 'maturity_date'],
      hideColumns: [],
      selectColumns: [
        'record_date',
        'account_nbr',
        'account_desc',
        'security_nbr',
        'segment_desc',
        'loans_receivable_amt',
        'interest_receivable_amt',
        'maturity_date',
        'interest_rate_pct',
        'amortization_amt',
        'capitalized_int_receivable_amt',
      ],
      apiFilter: {
        field: 'account_nbr',
        labelField: 'account_desc',
        downloadLabel: 'Account',
        label: 'Choose an Account',
        disableDateRangeFilter: true,
        dataDefaultHeader: 'This table requires additional filters.',
        dataDefaultMessage: 'Select an account in the filter section above to display the data.',
        dataUnmatchedHeader: 'There is no data to display based on the current filters selected.',
        dataUnmatchedMessage: 'Select a different account and/or date range in order to preview the data.',
        dataSearchLabel: 'Search account descriptions',
      },
    },
    // FBP
    '314': {
      endpoint: 'v1/accounting/od/fbp_future_dated_transactions',
      dateField: 'settle_date',
      downloadName: 'FBP_FutureDatedTransactions',
      alwaysSortWith: ['-sort_order_primary', '-sort_order_secondary', 'security_nbr'],
      hideColumns: [],
      selectColumns: [
        'record_date',
        'account_nbr',
        'account_desc',
        'security_nbr',
        'segment_desc',
        'loans_receivable_amt',
        'interest_receivable_amt',
        'effective_date',
        'settle_date',
        'transaction_cd',
        'memo_nbr',
        'amortization_amt',
        'capitalized_int_receivable_amt',
      ],
      apiFilter: {
        field: 'account_nbr',
        labelField: 'account_desc',
        downloadLabel: 'Account',
        label: 'Choose an Account',
        disableDateRangeFilter: true,
        dataDefaultHeader: 'This table requires additional filters.',
        dataDefaultMessage: 'Select an account in the filter section above to display the data.',
        dataUnmatchedHeader: 'There is no data to display based on the current filters selected.',
        dataUnmatchedMessage: 'Select a different account and/or date range in order to preview the data.',
        dataSearchLabel: 'Search account descriptions',
      },
    },
  },
};
