name: Accessibility Scan
on:
  workflow_call

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: be-a11y Accessibility Checker
        id: a11ychecker
        uses: be-lenka/be-a11y@v2.2.8
        continue-on-error: true
        with:
          url: ''
          report: 'report.json'

      - name: Upload accessibility report artifact
        if: steps.a11ychecker.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-report
          path: 'report.json'

      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
