
name: Run unit and e2e tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-unit-tests-and-coverage:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Create npmrc
        shell: bash
        run: |
          echo "registry=https://artifactory.prod.dt.ts.aws.frb.pvt/artifactory/api/npm/kc-dtas-npm/" > .npmrc
          echo "always-auth = true" >> .npmrc
          echo "noproxy=artifactory.prod.dt.ts.aws.frb.pvt" >> .npmrc
          echo "_auth = ${{ vars.ARTIFACTORY }}" >> .npmrc
      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.18
#          registry-url: https://artifactory.prod.dt.ts.aws.frb.pvt/artifactory/kc-dtas-npm/
      - run: |
          npm config fix
          npm ci --legacy-peer-deps --loglevel verbose
      - name: run tests with coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          NODE_AUTH_TOKEN: ${{ vars.ARTIFACTORY }}
        run: npm run test:coverage
  run-branch-unit-tests-and-coverage:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git fetch --no-tags --depth=1 origin master
          git checkout -b master origin/master
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: npm install
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm install --legacy-peer-deps
      - name: run branch tests with coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm run test:branch
  run-cypress-tests:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: Cypress install
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm install --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          GITHUB_TOKEN: ${{ github.token }}
        with:
          install: false
          build: npm run build
          start: npm run serve
          broswer: chrome
