
name: Run unit and e2e tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-unit-tests-and-coverage:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Create npmrc
        shell: bash
        run: |
          npm config set strict-ssl=false
          npm config set registry=artifactory.prod.dt.ts.aws.frb.pvt/kc-dtas-npm/
          npm config set proxy=http://j1proxy.frb.org:8080
          npm config set https-proxy=http://j1proxy.frb.org:8080
          npm config set http_proxy=http://j1proxy.frb.org:8080
          npm config set https_proxy=http://j1proxy.frb.org:8080
          npm config set //artifactory.prod.dt.ts.aws.frb.pvt/artifactory/kc-dtas-npm/:_auth=${{ vars.ARTIFACTORY }}
      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.18
      - run: |
          npm cache clean --force
          npm config ls -l
          npm install --loglevel verbose --legacy-peer-deps
      - name: run tests with coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm run test:coverage
  run-branch-unit-tests-and-coverage:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git fetch --no-tags --depth=1 origin master
          git checkout -b master origin/master
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: npm install
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm install --legacy-peer-deps
      - name: run branch tests with coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm run test:branch
  run-cypress-tests:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: Cypress install
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm install --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          GITHUB_TOKEN: ${{ github.token }}
        with:
          install: false
          build: npm run build
          start: npm run serve
          browser: chrome
