
name: PR Checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-unit-tests-and-coverage:
    name: Run Test Coverage
    uses: ./.github/workflows/run-unit-tests.yml
  run-branch-unit-tests-and-coverage:
    name: Run Branch Test Coverage
    uses: ./.github/workflows/run-branch-unit-tests.yml
  run-accessibility-scan:
    name: Run Accessibility Scan
    uses: ./.github/workflows/accessibility-scan.yml
#  run-cypress-tests:
#    name: Run Cypress Tests
#    uses: ./.github/workflows/run-cypress-tests.yml
