
name: Run unit and e2e tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-unit-tests-and-coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.19.0
      - name: npm install
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm install --legacy-peer-deps
      - name: run tests with coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm run test:coverage
  run-cypress-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.19.0
      - name: Cypress install
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm install --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          GITHUB_TOKEN: ${{ github.token }}
        with:
          install: false
          build: npm run build
          start: npm run serve
          broswer: chrome
